name: Linux Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Deploy-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install cmake devscripts debhelper mesa-common-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxcomposite-dev libglib2.0-0 libfontconfig1-dev mesa-vulkan-drivers libvulkan1 vulkan-tools vulkan-validationlayers

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build, Package and Test
        run: |
          export ASAN_OPTIONS=detect_leaks=0
          mkdir cmake_build
          cd cmake_build
          cmake -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DVISAGE_ADDRESS_SANITIZER=ON -DVISAGE_ENABLE_GRAPHICS_DEBUG_LOGGING=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G "Unix Makefiles" ..
          cmake --build . --target package --parallel
          ctest --output-on-failure
