name: MinGW Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build-MinGW:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: CMake build
        run: |
          mkdir cmake_build
          cd cmake_build
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release --parallel
          ctest --output-on-failure
